2025-07-11 11:54:23,355 - INFO - Sample train set 1500/67349
2025-07-11 11:54:23,355 - INFO - ... including dev set 500 samples
2025-07-11 11:54:23,355 - INFO - Loading model with FP16...
/home/rinya/anaconda3/envs/zollm/lib/python3.10/site-packages/huggingface_hub/file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
12
2025-07-11 11:54:27,985 - INFO - Done with 4.63s
Traceback (most recent call last):
  File "/home/rinya/zero-order-optimization/src/run.py", line 740, in <module>
    main()
  File "/home/rinya/zero-order-optimization/src/run.py", line 652, in main
    framework = Framework(args, task)
  File "/home/rinya/zero-order-optimization/src/run.py", line 185, in __init__
    self.model, self.tokenizer = self.load_model()
  File "/home/rinya/zero-order-optimization/src/run.py", line 249, in load_model
    model = AutoModelForCausalLM.from_pretrained(self.args.model_name, config=config, device_map='auto',
  File "/home/rinya/anaconda3/envs/zollm/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/home/rinya/anaconda3/envs/zollm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2795, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/rinya/anaconda3/envs/zollm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3123, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/rinya/anaconda3/envs/zollm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 698, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/home/rinya/anaconda3/envs/zollm/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 317, in set_module_tensor_to_device
    new_value = value.to(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacty of 39.50 GiB of which 7.81 MiB is free. Process 580758 has 37.33 GiB memory in use. Including non-PyTorch memory, this process has 2.14 GiB memory in use. Of the allocated memory 1.61 GiB is allocated by PyTorch, and 126.84 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF